### ISSUE TITLE
(BUG) Copy and Paste not working properly

### ISSUE THREAD

**Issue by AdamDenoon** [photokandyStudios/gbible#43]
(BUG) Copying and pasting is not working. Copying a verse actually puts NEXT verse on the clipboard. If last verse of Chapter is copied, app crashes.  If multiple verses are selected (even in correct order), they are pasted grossly out of order. Other than that, looks good. Thanks!

**Comment by AdamDenoon** [comment]
To fix the "NEXT" verse issue (which actually copies the next verse, or crashes if last verse of Chapter is selected), make the following changes in your "gBible>Controllers>Bible Controller>PKBibleViewController.m" implementation file (in your "-(void) copySelection: (id)sender" method):

[theText appendString:[currentEnglishChapter objectAtIndex:theVerse]];

AND

[theText appendString:[currentGreekChapter objectAtIndex:theVerse]];

SHOULD READ

[theText appendString:[currentEnglishChapter objectAtIndex:theVerse - 1]];

AND

[theText appendString:[currentGreekChapter objectAtIndex:theVerse - 1]];

(I tested this out and it works flawlessly. I haven't taken a look at the "multiple verse select out of order" issue yet. I hope this helps you out! :+1: )

**Comment by kerrishotts** [comment]
Thanks for the report and suggested fix. The out-of-order is really confusing... I'll have to play around with it and see why it is getting messed up.

**Comment by AdamDenoon** [comment]
Mr. Shotts,

```
 Thanks for getting back to me :) I LOVE your app. I use it every day for my own personal study, my sermons, my school work, and even in 1-on-1 ministry opportunities. I'm a software developer at Jimmy Swaggart Ministries, so I love the Lord AND programming ;)! I enjoy your app a lot, so anything I can do to help improve it, I'll do :) There are a couple of other, minor things, such as the disappearance of the shadow on the top edge of the scroll when you switch between modes (the Word, Strong's lookup, etc.) and that when you do multiple searches, and hide the keyboard, sometimes the "greyed out" search results don't "ungrey", which stops you from tapping them and being automatically brought to that passage. As for the Strong's numbers not working, what should say, in Mark 2:4 for example, "εξορύσσω (G1846): from G1537 (εκ) and G3736 (ορύσσω)", it merely repeats the whole word: "εξορύσσω (G1846): from G1537 (εξορύσσω) and G3736 (εξορύσσω)". It would be neat if you could press those root words and get definitions for them right in the app, and Copy and paste from the Strong's Lookup page would be a plus too, for notes/sermon writing purposes, if that's not too difficult. One other thing is the fact that if there's a compound verb (usually containing a prepositional proclitic), trying to get a definition of the second Greek number under it produces no results in the Strong's Lookup.
 I hope you're not offended and hassled by my suggestions. I'm just a firm advocate of it. I share it with many people as something they should purchase, and the people who see it are very impressed :) 
```

PS If you ever figure out how to replace the Greek text you have with some with diacritics, you'll be the first app I'll have ever seen (in much searching) that has the Greek text, the English text, parsing, definitions, and diacritics in one app! If that was ever the case, I'd find every professor and teacher I could around me, and if they have an iDevice, ensure that they know the value of buying your app!

Hope this helps!

**Comment by kerrishotts** [comment]
I'm flattered you like the app so much, and have taken the time to suggest improvements. I also want this app to be the best it can be, so there's no worry about offending or hassling me with ideas -- I'll gladly take any ideas, bug reports, etc., that you can think of.

Regarding some of the above, I've fixed the copy & paste off-by-one issue, and also fixed the out-of-order issue. Apparently the `selectedVerses NSMutableDictionary` doesn't return the results in any order /at all/, and hence the out-of-order results when copying multiple verses. Extracting the keys and sorting them seems to do the trick.

I've moved your other reports (shadows, search results grayed-out) to new bugs, and moved the Strong's info to the existing bug report so that I can keep track of them while also being able to close out this particular bug. 

Regarding the greek diacritics, you'll be happy to know that they are coming for the Westcott-Hort edition. I haven't found a source yet for the TR, TIS, or BYZ, so they'll continue to be non-diacritical, but it's a start. Furthermore, I was able to obtain the interlinear readings for WH, so the app will also be able to render the translation directly beneath the Greek as a true interlinear would do. The rendering isn't perfect, but it's also a start. It's already been checked-in, so if you want to compile it and give it a go, that would be great -- or, if you'd like to be a beta tester, you can sign up here: https://testflightapp.com/join/328b864c261f3e755f9bf680c864596b-NTkzMzg/

My goal (perhaps a bit unrealistic) is to get v1.1 out the door with time for Apple to approve it prior to their Dec 21-28 break. Not entirely sure I'll make it, but I'm sure going to make a go at it.

**Comment by AdamDenoon** [comment]
Your professionalism is awesome! I'm glad you figured out hte sorting on
the copy-paste... this will be a huge asset to my work! As for the
diacritics, I'm on the edge of my seat for the rest :) (I don't use the
Wescott-Hort because they seem to omit and change certain things... I
realize they use different manuscripts but it seems a bit "watered down" in
some places, and leaves out some (sometimes important) things... TIS does
the same. I love Textus Receptus the most!)

I joined the beta-test list, but didn't exactly receive confirmation... it
just seemed to refresh the page. Can you confirm that I've joined?)

PS Idea for searching diacritical text: If you can find the ascii codes for
diacritical characters, you should be able to recognize them in the search,
or at the very worst add conditional statements that compare them to their
english equivalents

On Wed, Dec 5, 2012 at 4:57 PM, Kerri Shotts notifications@github.comwrote:

> I'm flattered you like the app so much, and have taken the time to suggest
> improvements. I also want this app to be the best it can be, so there's no
> worry about offending or hassling me with ideas -- I'll gladly take any
> ideas, bug reports, etc., that you can think of.
> 
> Regarding some of the above, I've fixed the copy & paste off-by-one issue,
> and also fixed the out-of-order issue. Apparently the selectedVerses
> NSMutableDictionary doesn't return the results in any order /at all/, and
> hence the out-of-order results when copying multiple verses. Extracting the
> keys and sorting them seems to do the trick.
> 
> I've moved your other reports (shadows, search results grayed-out) to new
> bugs, and moved the Strong's info to the existing bug report so that I can
> keep track of them while also being able to close out this particular bug.
> 
> Regarding the greek diacritics, you'll be happy to know that they are
> coming for the Westcott-Hort edition. I haven't found a source yet for the
> TR, TIS, or BYZ, so they'll continue to be non-diacritical, but it's a
> start. Furthermore, I was able to obtain the interlinear readings for WH,
> so the app will also be able to render the translation directly beneath the
> Greek as a true interlinear would do. The rendering isn't perfect, but it's
> also a start. It's already been checked-in, so if you want to compile it
> and give it a go, that would be great -- or, if you'd like to be a beta
> tester, you can sign up here:
> https://testflightapp.com/join/328b864c261f3e755f9bf680c864596b-NTkzMzg/
> 
> My goal (perhaps a bit unrealistic) is to get v1.1 out the door with time
> for Apple to approve it prior to their Dec 21-28 break. Not entirely sure
> I'll make it, but I'm sure going to make a go at it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/photokandyStudios/gbible/issues/43#issuecomment-11065077.

##

**Comment by kerrishotts** [comment]
Hmm; I just checked and there's nothing new on TestFlight.

If you want, you can send me your email to kerrishotts@gmail.com and I'll send out an invite that way.

---

~Kerri Shotts, photoKandy Studios LLC
   Wanna be our neighbor? Our Facebook page & Twitter feed.

**Comment by AdamDenoon** [comment]
Alright :)
