### ISSUE TITLE
Other app stores

### ISSUE THREAD

**Issue by jerryevo** [photokandyStudios/gbible#58]
I suggest to put gBible to other App Stores - for example I can't buy it in Polish App Store

**Comment by kerrishotts** [comment]
I am exploring widening the release, however I must be sure about the KJV 
copyright status in each region. For example, the UK claims Crown Copyright, and 
as such this can not be released there without either removing the KJV or 
preventing access to it.

So it is definitely my intent to broaden the distribution, but it will take some time and
research in order to figure out the status of the KJV. If you have any specific
knowledge regarding its status in your region, I'd be happy to see it. If the KJV Is
public domain in your region, I would be happy to extend the reach to that area.

Also, the app itself is not yet localized, so if you or someone you know would like to 
work on a translation, I'd be ecstatic.

**Comment by jerryevo** [comment]
Hi again,

I'm from Poland and KJV is completely unusable here because we are speaking Polish :)
But I'm interested in greek bible.
I think that KJV is not covered by any copyright because it is too old :)

Regards,
Jarek

Wiadomoœæ napisana przez Kerri Shotts notifications@github.com w dniu 8 sty 2013, o godz. 21:20:

**Comment by kerrishotts** [comment]
Do you know of a freely available public-domain Polish Bible that aims for a literal
translation? I'm exploring the future option of having downloadable Bibles, but not
native speaker of your language, I don't know what translations would be
equivalent to, say, the KJV or YLT where they are aiming more for a literal translation
than a paraphrase. (Not that I'm against either -- just that a literal translation fits
better in this context.)

**Comment by jerryevo** [comment]
Much better is to "cache" Bible from internet.
Trick is that when browsing verses they are taken directly from internet server which has this Bible translation.
You can give user chooice to pre download all Bible but still it is not from your server.

For Polish translations you can use: http://www.biblia.info.pl/biblia.php
There are most interesting Polish translations:
Biblia Tysi¹clecia
Biblia Warszawska
Biblia Warszawsko-Praska
Biblia Gdañska - btw. this is old translation and is 100% not copyrighted
Biblia Brzeska
Biblia Poznañska
Przek³ad Nowego Œwiata (you can know it's version in other languages as New World Translation).

I can help you in preparing Polish translation and tests if you want to.

I personally prefer New World Translation as most accurate in Polish.

Regards,

Jarek

Wiadomoœæ napisana przez Kerri Shotts notifications@github.com w dniu 8 sty 2013, o godz. 23:46:

**Comment by kerrishotts** [comment]
I just wanted to let you know that I've checked in the Localizable.strings file for Polish if you want to have a crack at it. The about.html also needs translated, but only do so if you feel like it. 

Also -- would you like to be a beta tester? If so, just send me your email to kerrishotts@gmail.com so I can send you a TestFlight invite.

**Comment by kerrishotts** [comment]
Latest commit (Build 4775) has initial support for region-locking the KJV edition. Current exclusion areas include the UK, the Eurozone, Canada, and Australia. The latter under the quite-possibly-erroneous assumption that they would need to respect the UK's copyright if the UK ever decided to enforce it. Not sure how the Eurozone would deal with that if it happened, but better safe than sorry.

**Comment by kerrishotts** [comment]
Latest commit (Build 4776) removes region locking for CA and AU. I'm leaving the rest of the Eurozone for now. I doubt it's terribly problematic as it would ultimately be preferable to have a native language Bible where needed.

**Comment by jerryevo** [comment]
Hi,

Attached you have localizable.strings translated to Polish.
I'm not sure what you mean as "passage"

BTW: there are missing some book names:
Numbers
Ecclesiastes

I suggest changing icon to the one not having cross - not all Bible lovers are Cross lovers

Regards,

Jarek

Wiadomoœæ napisana przez Kerri Shotts notifications@github.com w dniu 9 sty 2013, o godz. 07:05:

**Comment by kerrishotts** [comment]
Thanks!

I don't seem to see the attachment, though. 

Thanks for the heads-up on the missing books… The keys were typed by hand, so I knew I'd miss one or two somewhere. My eyes aren't what they once were anymore!

As to "passage" -- I'm referring to a verse reference; for example, John 3:16 is considered a passage. 

What icon are you referring to? The application icon? or the cross symbol in the translation strings? That one's just intended as a second symbol to the asterisk; I could have used **, but that just looks… painful, to me.

I've got your device profile, so you should be able to use the next beta that I send with TestFlight. Thanks for joining up! :-)

**Comment by jerryevo** [comment]
Sending again - this time zipped.

I was talking about application icon.

Jarek

Wiadomoœæ napisana przez Kerri Shotts notifications@github.com w dniu 10 sty 2013, o godz. 00:16:

**Comment by kerrishotts** [comment]
Ok, I think GitHub is getting in the way here. Try sending the translation file to my email instead: kerrishotts@gmail.com. 

As to the application icon, well… There's a story there, and from the sounds of it, you were affected by a copycat.

The proper application icon has three greek letters on a blue background with some chrome around the edges (you can see it on the iTunes app page: https://itunes.apple.com/us/app/greek-interlinear-bible/id520000138?mt=8). The Icon you're referring to must be an infringing app I caught wind of a few days ago. Which is going to be problematic, because my app won't upgrade on top of it -- it'll install separately.

So -- if you've got any notes, highlights, etc., that you want to transfer, be sure to:
 1) Use the export functionality in the Settings page. This should create a file in iTunes that you can download to your computer.
 2) When you install the beta version from TestFlight, copy that file to the app using iTunes. Be sure to rename the file "import.dat"
 3) Open the beta version, Go to Settings, and tap "import everything".

I'd give you a gift code right now to get the proper version from the app store, but since that version is quite old, it'd be little use. Instead, when Apple puts 1.1 on the store, I'll send you a gift code then. That way you can have the proper app installed. In the mean time, the beta version will suffice nicely.

On a side note -- once you get all your settings, notes, etc. transferred to the beta version, I really would suggest deleting the infringing copy. The infringer didn't make his code changes available so I have no idea what else he added… which means he could have added malicious code. It's good that we're on iOS, so any malicious code would be pretty limited in scope, but better safe than sorry.

**Comment by jerryevo** [comment]
I didn't instal your app nor copycat app - I was just looking on icon.
Because I had Polish App Store account I'm not able to buy in US App Store :)

Wiadomość napisana przez Kerri Shotts notifications@github.com w dniu 10 sty 2013, o godz. 00:44:

> Ok, I think GitHub is getting in the way here. Try sending the translation file to my email instead: kerrishotts@gmail.com. 
> 
> As to the application icon, well… There's a story there, and from the sounds of it, you were affected by a copycat. 
> 
> The proper application icon has three greek letters on a blue background with some chrome around the edges (you can see it on the iTunes app page: https://itunes.apple.com/us/app/greek-interlinear-bible/id520000138?mt=8). The Icon you're referring to must be an infringing app I caught wind of a few days ago. Which is going to be problematic, because my app won't upgrade on top of it -- it'll install separately. 
> 
> So -- if you've got any notes, highlights, etc., that you want to transfer, be sure to: 
> 1) Use the export functionality in the Settings page. This should create a file in iTunes that you can download to your computer. 
> 2) When you install the beta version from TestFlight, copy that file to the app using iTunes. Be sure to rename the file "import.dat" 
> 3) Open the beta version, Go to Settings, and tap "import everything". 
> 
> I'd give you a gift code right now to get the proper version from the app store, but since that version is quite old, it'd be little use. Instead, when Apple puts 1.1 on the store, I'll send you a gift code then. That way you can have the proper app installed. In the mean time, the beta version will suffice nicely. 
> 
> On a side note -- once you get all your settings, notes, etc. transferred to the beta version, I really would suggest deleting the infringing copy. The infringer didn't make his code changes available so I have no idea what else he added… which means he could have added malicious code. It's good that we're on iOS, so any malicious code would be pretty limited in scope, but better safe than sorry. 
>

**Comment by kerrishotts** [comment]
Okay -- I'm glad you aren't affected by the copycat. You must've seen his icon, though, instead; mine doesn't have a cross in it anywhere.

**Comment by kerrishotts** [comment]
Ha -- My headache must be getting in the way of my actual thinking... of course you couldn't install it, or you wouldn't have opened the issue here... 

I must go get some pain meds, apparently.

Also -- received your translations... Beautiful! Thank you SO much. You'll get a gift code for the 1.1 version when it goes online. I'll be opening 1.1 to all areas (I think I've satisfied the KJV copyright on my end), so you'll be able to grab a copy of the non-beta version.

Again, thanks SO much. :-)

**Comment by kerrishotts** [comment]
Build 4790 has Polish. Thanks to @jerryevo. They look gorgeous!

**Comment by kerrishotts** [comment]
Closing as we're in all but the UK. Waiting on the UK until I get information from Cambridge on the KJV.
