### ISSUE TITLE
Launch image fadeout animation on landscape

### ISSUE THREAD

**Issue by jcesarmobile** [photokandyStudios/gbible#74]
When you launch the app on landscape, the fade out animation of the launch image shows the image on portrait

**Comment by kerrishotts** [comment]
I assume this is for iPhone? Yes, it does funny things there, doesn't it...

**Comment by kerrishotts** [comment]
No easy solution, as far as I can tell. There's no way to give it a landscape-style splash until the app gets control, and by the time the app gets control the splash has already been displayed by the OS. So switching the splash would be problematic. 

The only thing I know to do is to remove the splash screen upon the detection of rotation, which the view does get upon launch. The transition is abrupt, but is the only thing I know to do. At least it doesn't look so odd :-)

**Comment by jcesarmobile** [comment]
No, the problem was on the iPad, I didn't tested on my iPod.

The problem was, the app displays the landscape launch image because the app was in landscape (as expected), and then, when you do the fadeout animation, the image you use for the fade out animation was a portrait image, I mean, it was correctly oriented (text readable on landscape) but with portrait size.

**Comment by kerrishotts** [comment]
The only time I saw that was if the device was rotated as the app opened.
The latest code fixes that.

OTH, if you're seeing the wrong splash image with no intervening
orientation change, odd. What version of OS and iteration of iPad?

On Feb 19, 2013, at 4:09, "Julio César" notifications@github.com wrote:

No, the problem was on the iPad, I didn't tested on my iPod.

The problem was, the app displays the landscape launch image because the
app was in landscape (as expected), and then, when you do the fadeout
animation, the image you use for the fade out animation was a portrait
image, I mean, it was correctly oriented (text readable on landscape) but
with portrait size.

—
Reply to this email directly or view it on
GitHubhttps://github.com/photokandyStudios/gbible/issues/74#issuecomment-13765268.

**Comment by jcesarmobile** [comment]
It's not happening on the latest version, in fact, there is no fade out animation on the latest version xD

I just wanted to explain the bug a bit better in case you want to implement the fade out animation again

**Comment by kerrishotts** [comment]
Odd. 

I'm getting a fade here. What iOS version? iPad 1, 2, 3, etc.?

**Comment by jcesarmobile** [comment]
Not working on iPad 2 5.0.1 and iPod touch 4G 5.1
Working on iPad 4 6.1

**Comment by kerrishotts** [comment]
Hmmm,... It must be iOS 5 related. I haven't seen the simulator do anything odd with iOS 5, but hey - it does a lot of things the real devices do and vice versa...
