### ISSUE TITLE
Strong remember the search term, but not the search result

### ISSUE THREAD

**Issue by jcesarmobile** [photokandyStudios/gbible#76]
STR
1. Go to strongs tab
2. Search something
3. Quit the app
4. Force close of the app
5. Open the app
6. Go to the strongs tab
You'll see the search term, but not the search result.
It should remember both or none of them.
And it should be consistent with the search tab

**Comment by kerrishotts** [comment]
Somewhat by design -- I don't want the first load of the Strong's tab to take a long time in case the search was a really complicated one. Since the history maintains the last search, I'm not sure how important it is that the search bar retains the last search, especially with some of the new changes (where the view can be used in many different places).

**Comment by kerrishotts** [comment]
For now I'm letting the search controllers remember the search term without remembering the search result -- mainly because a complicated search term could cause the initial load of the view to take considerable time. I have added text, however, that indicates that a re-search will display the results.

I did, however, make Search/Strong's consistent in that they both remember the previous search term.
